### ISSUE TITLE
issues encounter when I run other yml files

### ISSUE THREAD

**Issue by henryliuliuliu** [zhouxian/FluidLab#7]
Specifically, when I run` python fluidlab/run.py --cfg_file configs/exp_gathering_easy.yaml --record`
it reports:
`aceback (most recent call last):
  File "fluidlab/run.py", line 63, in <module>
    main()
  File "fluidlab/run.py", line 41, in main
    env = gym.make(cfg.EXP.env_name, seed=cfg.EXP.seed, loss=False, loss_type='diff', renderer_type=args.renderer_type)
  File "C:\Users\Shipe\miniconda3\envs\fluidlab\lib\site-packages\gym\envs\registration.py", line 200, in make
    return registry.make(id, **kwargs)
  File "C:\Users\Shipe\miniconda3\envs\fluidlab\lib\site-packages\gym\envs\registration.py", line 105, in make
    env = spec.make(**kwargs)
  File "C:\Users\Shipe\miniconda3\envs\fluidlab\lib\site-packages\gym\envs\registration.py", line 75, in make
    env = cls(**_kwargs)
  File "c:\users\shipe\dropbox\myworkspace\fluidlab\fluidlab\envs\gatheringeasy_env.py", line 35, in __init__
    self.build_env()
  File "c:\users\shipe\dropbox\myworkspace\fluidlab\fluidlab\envs\fluid_env.py", line 38, in build_env
    self.setup_bodies()
  File "c:\users\shipe\dropbox\myworkspace\fluidlab\fluidlab\envs\gatheringeasy_env.py", line 69, in setup_bodies
    material=RIGID,
  File "c:\users\shipe\dropbox\myworkspace\fluidlab\fluidlab\fluidengine\taichi_env.py", line 93, in add_body
    self.particle_bodies.add_body(**kwargs)
  File "c:\users\shipe\dropbox\myworkspace\fluidlab\fluidlab\fluidengine\bodies\bodies.py", line 40, in add_body
    self.add_mesh(filling=filling, **kwargs)
  File "c:\users\shipe\dropbox\myworkspace\fluidlab\fluidlab\fluidengine\bodies\bodies.py", line 199, in add_mesh
    voxels = pkl.load(open(voxelized_file_path, 'rb'))
AttributeError: 'TrackedArray' object has no attribute 'fast_hash'`.
When I run: 
`python fluidlab/run.py --cfg_file configs/exp_mixing.yaml --record`
Traceback (most recent call last):
  File "fluidlab/run.py", line 63, in <module>
    main()
  File "fluidlab/run.py", line 44, in main
    record_target(env, path=args.path, user_input=args.user_input)
  File "c:\users\shipe\dropbox\myworkspace\fluidlab\fluidlab\optimizer\recorder.py", line 107, in record_target
    recorder.record(user_input)
  File "c:\users\shipe\dropbox\myworkspace\fluidlab\fluidlab\optimizer\recorder.py", line 16, in record
    policy = self.env.demo_policy(user_input)
TypeError: demo_policy() takes 1 positional argument but 2 were given.`
There are some other issues with renderred_type, but I assume that following the latter_art.env, we could solve this~ 
Is there a plan to have documentation about how to generate the paper results? 
Best,
Shipeng

**Comment by henryliuliuliu** [comment]
I am wondering if the algorithm used to compare with the DP is here.  If I want to get the result of SAC, etc, what should I do to minimize the efforts?  Thanks very much!

**Comment by henryliuliuliu** [comment]
AttributeError: 'TrackedArray' object has no attribute 'fast_hash' this error can be solved by deleting the file and regenerate

**Comment by zhouxian** [comment]
I tried `exp_gathering_easy.yaml` and it seems ok on my end. Maybe it's a package version mismatch issue? Did you create your env using `environment.yml`?
Anyhow, glad you found a solution.

For baselines, we simply used stable baselines (https://github.com/DLR-RM/stable-baselines3), and we didn't include it in our released repo to avoid making it too messy.

**Comment by henryliuliuliu** [comment]
I am wondering if there is a way to simulate a real rigid robot with joint？
and did you calculate the interaction force between robot and
endeffector，in other words， can I do force control？

Best，
Shipeng

**Comment by zhouxian** [comment]
Interesting you asked - current fluid lab doesn't have serious rigid body dynamics, not to mention articulated body such as robot arm.
However, we are indeed working on a revolutionary platform that will support an advanced rigid body physics engine, with also coupling with other materials. In addition, we are adding support for other physics solvers such as PBD, SPH, FEM and more (current fluidlab only has MPM). We also redesigned the whole infrastructure and now the gradient access is 100x easier than fluidlab.
It's still under development and we will try to have a alpha release probably next month or so. Let me know if you want to know more. We can have a chat if you want and possibly add you to our private repo.

**Comment by henryliuliuliu** [comment]
The project you mentioned looks promising. My goal is to add a quadruped
robot scenario， and run  the robot in various fluid. If you could add me to
the repo, that would be great!

Best,
Shipeng
